# Setup
title:               Medieval Networks of Memory
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://hannahkim24.github.io
baseurl:             '/mnm'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hannah Kim
  url:               
  email:             hkim24@stanford.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
